apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.Namespace }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Riyadh
          image: >-
            {{ .Values.global.IMAGE_BASE_URL }}/{{ .Release.Namespace }}/{{ .Chart.Name }}:1
          imagePullPolicy: Always
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 7006
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.global.cpu_limit.absher_log_service}}
              memory: {{ .Values.global.ram_limit.absher_log_service }}
            requests:
              cpu: {{ .Values.global.cpu_request.absher_log_service }}
              memory: {{ .Values.global.ram_request.absher_log_service }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/src/app/logs
              name: logging-storage		
              subPath: {{ .Chart.Name }}
            - mountPath: /usr/src/app/.env
              name: {{ .Chart.Name }}-configmap
              subPath: .env
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logging-storage
          persistentVolumeClaim:
            claimName: applogs	
        - configMap:
            defaultMode: 420
            name: {{ .Chart.Name }}-configmap
          name: {{ .Chart.Name }}-configmap
