apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: 7006-tcp
      port: 7006
      protocol: TCP
      targetPort: 7006
      nodePort: 30006  # Specify the node port you want to use, or omit to use a random available port
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: NodePort  # Change the type to NodePort
status:
  loadBalancer: {}
