apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - name: 7006-tcp
      port: 7006
      protocol: TCP
      targetPort: 7006
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

